export const FILTER_UPDATE = 'FILTER_UPDATE';
export const TASK_UPDATE_COMPLETED = 'TASK_UPDATE_COMPLETED';
export const ADD_TASK = 'ADD_TASK';
export const DELETE_TASK = 'DELETE_TASK';
export const DELETE_COMPLETED_TASK = 'DELETE_COMPLETED_TASK';
